### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Janbuller** [HarshWombat/fessorBot#1]
Adding a README.MD might aid others at using the Bots.

**Comment by HarshWombat** [comment]
Since MatematikFessor is a Danish website, I'll assume you are Danish. If that's not the case, I'll be happy to switch back to English.

Dette projekt er mere eller mindre forladt og havde ikke lige forventet at andre ville have interesse i det. Jeg vil nu gå i gang med en ReadMe, dog vil jeg gøre opmærksom på at alle XP givende opgaver kræver en browser extension (F.eks WebKit eller Mozilla), fordi det kræver at scriptet ikke bliver påvirket af et site-change. Hvis dette ikke er hvad du leder efter, kan jeg varmt anbefale [http://mldx.dk/fessorbot.php](url), jeg har testet den, men har ikke set kildekoden eller haft noget med udviklingen.
